//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PIZCms.rc
//

// LIBPIZIOT 2007/01/09, pizillaorg@gmail.com
// The solution for build your own IoT software infrastructure

#define IDD_ABOUTBOX 100
#define IDP_OLE_INIT_FAILED 100
#define IDR_MAINFRAME 128
#define IDR_PIZCmsTYPE 129

#define IDC_CURSOR_HAND 500
#define IDB_BUTTON_NORMAL 621
#define IDB_BUTTON_FOCUS 622
#define IDB_BUTTON_DOWN 623
#define IDB_BUTTON_DISABLE 624

#define IDB_DIALOG_LIST_NORMAL 1000
#define IDB_DIALOG_LIST_FOCUS 0
#define IDB_DIALOG_LIST_DOWN 0
#define IDB_DIALOG_LIST_DISABLE 0

#define IDB_BUTTON_ON_NORMAL 1001
#define IDB_BUTTON_ON_FOCUS 1002
#define IDB_BUTTON_ON_DOWN 0
#define IDB_BUTTON_ON_DISABLE 0
#define IDB_BUTTON_OFF_NORMAL 1005
#define IDB_BUTTON_OFF_FOCUS 1006
#define IDB_BUTTON_OFF_DOWN 0
#define IDB_BUTTON_OFF_DISABLE 0

#define IDB_BUTTON_RETURN_NORMAL 1098
#define IDB_BUTTON_RETURN_FOCUS 1099
#define IDB_BUTTON_RETURN_DOWN 0
#define IDB_BUTTON_RETURN_DISABLE 0

#define IDB_DIALOG_TEST_NORMAL 2000
#define IDB_DIALOG_TEST_FOCUS 0
#define IDB_DIALOG_TEST_DOWN 0
#define IDB_DIALOG_TEST_DISABLE 0

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 10000
#define _APS_NEXT_CONTROL_VALUE 1000
#define _APS_NEXT_SYMED_VALUE 10000
#define _APS_NEXT_COMMAND_VALUE 32771
#endif
#endif
